<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/Encoders/ProtoBuf/ProtoBufEncoderTest.proto

namespace GPBMetadata\Test\Encoders\ProtoBuf;

class ProtoBufEncoderTest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad4010a30746573742f456e636f646572732f50726f746f4275662f5072" .
            "6f746f427566456e636f646572546573742e70726f746f2297010a065065" .
            "72736f6e120c0a046e616d65180120012809120b0a036167651802200128" .
            "05120f0a076164647265737318032001280912270a086368696c6472656e" .
            "180a2003280b32152e506572736f6e2e4368696c6472656e456e7472791a" .
            "380a0d4368696c6472656e456e747279120b0a036b657918012001280912" .
            "160a0576616c756518022001280b32072e506572736f6e3a023801620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

