<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/Encoders/ProtoBuf/ProtoBufEncoderTest.proto

namespace Nats\Test\Encoders\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <code>int32 age = 2;</code>
     */
    private $age = 0;
    /**
     * <code>string address = 3;</code>
     */
    private $address = '';
    /**
     * <code>map&lt;string, .Person&gt; children = 10;</code>
     */
    private $children;

    public function __construct() {
        \GPBMetadata\Test\Encoders\ProtoBuf\ProtoBufEncoderTest::initOnce();
        parent::__construct();
    }

    /**
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>int32 age = 2;</code>
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * <code>int32 age = 2;</code>
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;
    }

    /**
     * <code>string address = 3;</code>
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * <code>string address = 3;</code>
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;
    }

    /**
     * <code>map&lt;string, .Person&gt; children = 10;</code>
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * <code>map&lt;string, .Person&gt; children = 10;</code>
     */
    public function setChildren(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Person::class);
        $this->children = $arr;
    }

}

